/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#835500",
        "on-secondary-container": "#4e5d7e",
        "outline": "#857462",
        "on-tertiary-container": "#004d6a",
        "surface-container": "#eceef1",
        "surface-bright": "#f7f9fc",
        "inverse-on-surface": "#eff1f4",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#001e2c",
        "on-secondary-fixed": "#0a1b39",
        "background": "#f7f9fc",
        "inverse-surface": "#2d3133",
        "primary-fixed-dim": "#ffb955",
        "on-primary-container": "#644000",
        "on-primary-fixed": "#291800",
        "surface-container-low": "#f2f4f7",
        "on-error-container": "#93000a",
        "secondary-fixed": "#d8e2ff",
        "on-tertiary-fixed-variant": "#004c69",
        "on-secondary": "#ffffff",
        "on-background": "#191c1e",
        "tertiary": "#00658a",
        "surface-tint": "#835500",
        "surface-dim": "#d8dadd",
        "tertiary-container": "#3ac2ff",
        "surface-container-highest": "#e0e3e6",
        "tertiary-fixed": "#c4e7ff",
        "primary-fixed": "#ffddb4",
        "secondary": "#505e80",
        "on-secondary-fixed-variant": "#384667",
        "on-surface": "#191c1e",
        "inverse-primary": "#ffb955",
        "surface-container-high": "#e6e8eb",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#b7c6ed",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e0e3e6",
        "on-primary-fixed-variant": "#633f00",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "primary-container": "#f5a623",
        "on-surface-variant": "#524534",
        "secondary-container": "#c8d7fe",
        "surface": "#f7f9fc",
        "tertiary-fixed-dim": "#7cd0ff",
        "outline-variant": "#d7c3ae",
        "navy": "#0a1b39",
        "amber": "#f5a623",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
}
